"""001 — Community edition baseline schema.

A single squashed migration for a fresh community install. Generated from the
ORM models, plus the expression / partial indexes the models don't declare and
the pre-seeded Claude.ai MCP client.

Revision ID: 001_community_baseline
Revises:
Create Date: 2026-09-25
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_community_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('audit_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('info_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='complete', nullable=False),
    sa.Column('triggered_by', sa.String(length=16), server_default='claude', nullable=False),
    sa.Column('url_tested', sa.Text(), nullable=True),
    sa.Column('ltt_session_id', sa.String(length=64), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('sdr_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("audit_type IN ('tag_audit','live_tag_test','data_quality','sdr_compliance','platform_health','seo','warehouse','full_suite')", name='ck_audit_runs_type'),
    sa.CheckConstraint("status IN ('running','complete','error')", name='ck_audit_runs_status'),
    sa.CheckConstraint("triggered_by IN ('claude','schedule','manual')", name='ck_audit_runs_triggered_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_project_id'), 'audit_runs', ['project_id'], unique=False)
    op.create_table('ltt_test_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interaction_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ltt_test_plans_project_id'), 'ltt_test_plans', ['project_id'], unique=False)
    op.create_table('mcp_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('tag_custom_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('event', sa.String(length=128), server_default='*', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_params', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('forbidden_params', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('param_assertions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('severity', sa.String(length=16), server_default='warning', nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('critical','warning','info')", name='ck_tag_custom_rules_severity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'rule_id', name='uq_tag_custom_rules_project_rule')
    )
    op.create_index(op.f('ix_tag_custom_rules_project_id'), 'tag_custom_rules', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.String(length=16), server_default='client', nullable=False),
    sa.Column('tutorial_completed_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(length=16), server_default='google', nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deactivated_by_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('preferred_ai_client', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_email'), 'access_requests', ['email'], unique=False)
    op.create_table('ai_provider_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('audit_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('event', sa.String(length=128), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('entity_label', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='rule_book', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_project_id'), 'audit_findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_run_id'), 'audit_findings', ['run_id'], unique=False)
    op.create_table('mcp_auth_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_code_unused_valid', 'mcp_auth_codes', ['code', 'used', 'expires_at'], unique=False)
    op.create_index(op.f('ix_mcp_auth_codes_expires_at'), 'mcp_auth_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_mcp_auth_codes_used'), 'mcp_auth_codes', ['used'], unique=False)
    op.create_index(op.f('ix_mcp_auth_codes_user_id'), 'mcp_auth_codes', ['user_id'], unique=False)
    op.create_table('mcp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='oauth', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('token_hint', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_hash'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_user_active', 'mcp_sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_mcp_sessions_access_token_expires_at'), 'mcp_sessions', ['access_token_expires_at'], unique=False)
    op.create_index(op.f('ix_mcp_sessions_is_revoked'), 'mcp_sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_mcp_sessions_user_id'), 'mcp_sessions', ['user_id'], unique=False)
    op.create_table('oauth_app_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.LargeBinary(), nullable=False),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('configured_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("platform IN ('google', 'meta', 'tiktok', 'snap', 'linkedin', 'pinterest', 'x', 'reddit', 'bing', 'apple')", name='ck_oauth_app_credentials_platform_valid'),
    sa.ForeignKeyConstraint(['configured_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dashboard_style_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rbac_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_project_id'), 'activity_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_table('adjust_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adjust_project_user_active', 'adjust_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_adjust_connections_connection_status'), 'adjust_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_adjust_connections_is_active'), 'adjust_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_adjust_connections_project_id'), 'adjust_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_adjust_connections_user_id'), 'adjust_connections', ['user_id'], unique=False)
    op.create_table('adobe_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('client_id_encrypted', sa.Text(), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('has_analytics', sa.Boolean(), nullable=False),
    sa.Column('has_launch', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adobe_project_user_active', 'adobe_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_adobe_connections_company_id'), 'adobe_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_adobe_connections_connection_status'), 'adobe_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_adobe_connections_is_active'), 'adobe_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_adobe_connections_org_id'), 'adobe_connections', ['org_id'], unique=False)
    op.create_index(op.f('ix_adobe_connections_project_id'), 'adobe_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_adobe_connections_user_id'), 'adobe_connections', ['user_id'], unique=False)
    op.create_table('amplitude_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_amplitude_project_user_active', 'amplitude_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_amplitude_connections_connection_status'), 'amplitude_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_amplitude_connections_is_active'), 'amplitude_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_amplitude_connections_project_id'), 'amplitude_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_amplitude_connections_user_id'), 'amplitude_connections', ['user_id'], unique=False)
    op.create_table('appsflyer_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appsflyer_project_user_active', 'appsflyer_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_appsflyer_connections_connection_status'), 'appsflyer_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_appsflyer_connections_is_active'), 'appsflyer_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_appsflyer_connections_project_id'), 'appsflyer_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_appsflyer_connections_user_id'), 'appsflyer_connections', ['user_id'], unique=False)
    op.create_table('audit_finding_triage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_run_id', sa.UUID(), nullable=True),
    sa.Column('snoozed_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','resolved','snoozed')", name='ck_audit_finding_triage_status'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snoozed_run_id'], ['audit_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_audit_finding_triage_project_fp')
    )
    op.create_index(op.f('ix_audit_finding_triage_project_id'), 'audit_finding_triage', ['project_id'], unique=False)
    op.create_table('audit_vendors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('url_pattern', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('catalog_slug', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_audit_vendors_project_slug')
    )
    op.create_index(op.f('ix_audit_vendors_project_id'), 'audit_vendors', ['project_id'], unique=False)
    op.create_table('bq_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fluxito_project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('datasets', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('service_account_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fluxito_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bq_project_user_active', 'bq_connections', ['fluxito_project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_bq_connections_connection_status'), 'bq_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_bq_connections_fluxito_project_id'), 'bq_connections', ['fluxito_project_id'], unique=False)
    op.create_index(op.f('ix_bq_connections_is_active'), 'bq_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_bq_connections_project_id'), 'bq_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_bq_connections_user_id'), 'bq_connections', ['user_id'], unique=False)
    op.create_table('branch_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_branch_project_user_active', 'branch_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_branch_connections_connection_status'), 'branch_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_branch_connections_is_active'), 'branch_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_branch_connections_project_id'), 'branch_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_branch_connections_user_id'), 'branch_connections', ['user_id'], unique=False)
    op.create_table('braze_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('rest_endpoint_url', sa.String(length=255), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_braze_project_user_active', 'braze_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_braze_connections_connection_status'), 'braze_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_braze_connections_is_active'), 'braze_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_braze_connections_project_id'), 'braze_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_braze_connections_user_id'), 'braze_connections', ['user_id'], unique=False)
    op.create_table('business_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_contexts_project_id'), 'business_contexts', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_project_user', 'conversations', ['project_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_question', sa.Text(), nullable=True),
    sa.Column('interpretation_guide', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('time_grain', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('format_spec', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('target_value', sa.Numeric(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('expected_range_min', sa.Numeric(), nullable=True),
    sa.Column('expected_range_max', sa.Numeric(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('source_of_truth_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IS NULL OR direction IN ('higher_better','lower_better','neutral')", name='ck_kpis_direction'),
    sa.CheckConstraint("status IN ('draft','approved','deprecated')", name='ck_kpis_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_project_id'), 'kpis', ['project_id'], unique=False)
    op.create_table('marketo_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('instance_url', sa.String(length=512), nullable=False),
    sa.Column('client_id_encrypted', sa.Text(), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketo_project_user_active', 'marketo_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_marketo_connections_connection_status'), 'marketo_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_marketo_connections_is_active'), 'marketo_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketo_connections_project_id'), 'marketo_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_marketo_connections_user_id'), 'marketo_connections', ['user_id'], unique=False)
    op.create_table('mixpanel_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mixpanel_project_user_active', 'mixpanel_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_mixpanel_connections_connection_status'), 'mixpanel_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_mixpanel_connections_is_active'), 'mixpanel_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_mixpanel_connections_project_id'), 'mixpanel_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_mixpanel_connections_user_id'), 'mixpanel_connections', ['user_id'], unique=False)
    op.create_table('moengage_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('data_center', sa.String(length=32), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moengage_project_user_active', 'moengage_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_moengage_connections_connection_status'), 'moengage_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_moengage_connections_is_active'), 'moengage_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_moengage_connections_project_id'), 'moengage_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_moengage_connections_user_id'), 'moengage_connections', ['user_id'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'provider', 'google_email', name='uq_user_project_provider_email')
    )
    op.create_index(op.f('ix_oauth_connections_connection_status'), 'oauth_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_oauth_connections_is_active'), 'oauth_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_oauth_connections_project_id'), 'oauth_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_oauth_connections_provider'), 'oauth_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.create_index('ix_oauth_project_active_provider', 'oauth_connections', ['project_id', 'is_active', 'provider'], unique=False)
    op.create_index('ix_oauth_user_active_provider', 'oauth_connections', ['user_id', 'is_active', 'provider'], unique=False)
    op.create_table('posthog_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('project_host', sa.String(length=512), nullable=False),
    sa.Column('external_project_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posthog_project_user_active', 'posthog_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_posthog_connections_connection_status'), 'posthog_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_posthog_connections_is_active'), 'posthog_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_posthog_connections_project_id'), 'posthog_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_posthog_connections_user_id'), 'posthog_connections', ['user_id'], unique=False)
    op.create_table('project_email_senders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=16), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('smtp', 'ses')", name='ck_email_sender_type_valid'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_email_senders_project_id'), 'project_email_senders', ['project_id'], unique=False)
    op.create_table('project_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_project_invites_email'), 'project_invites', ['email'], unique=False)
    op.create_index('ix_project_invites_project_email_status', 'project_invites', ['project_id', 'email', 'status'], unique=False)
    op.create_index(op.f('ix_project_invites_project_id'), 'project_invites', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='member', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='ck_project_member_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_table('project_oauth_app_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.LargeBinary(), nullable=False),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('configured_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("platform IN ('google', 'meta', 'tiktok', 'snap', 'linkedin', 'pinterest', 'x', 'reddit', 'bing', 'apple')", name='ck_project_oauth_app_credentials_platform_valid'),
    sa.ForeignKeyConstraint(['configured_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'platform', name='uq_project_oauth_app_platform')
    )
    op.create_index(op.f('ix_project_oauth_app_credentials_project_id'), 'project_oauth_app_credentials', ['project_id'], unique=False)
    op.create_table('project_slack_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('webhook_url_encrypted', sa.Text(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=16), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_slack_webhooks_project_id'), 'project_slack_webhooks', ['project_id'], unique=False)
    op.create_table('redshift_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('host_encrypted', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username_encrypted', sa.Text(), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('default_schema', sa.String(length=255), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redshift_project_user_active', 'redshift_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_redshift_connections_connection_status'), 'redshift_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_redshift_connections_database'), 'redshift_connections', ['database'], unique=False)
    op.create_index(op.f('ix_redshift_connections_is_active'), 'redshift_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_redshift_connections_project_id'), 'redshift_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_redshift_connections_user_id'), 'redshift_connections', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_role_project_name')
    )
    op.create_index(op.f('ix_roles_project_id'), 'roles', ['project_id'], unique=False)
    op.create_table('snowflake_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('account_encrypted', sa.Text(), nullable=False),
    sa.Column('username_encrypted', sa.Text(), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('warehouse', sa.String(length=255), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('default_schema', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snowflake_project_user_active', 'snowflake_connections', ['project_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_connection_status'), 'snowflake_connections', ['connection_status'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_database'), 'snowflake_connections', ['database'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_is_active'), 'snowflake_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_project_id'), 'snowflake_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_user_id'), 'snowflake_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_snowflake_connections_warehouse'), 'snowflake_connections', ['warehouse'], unique=False)
    op.create_table('test_flows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('device', sa.String(length=16), server_default='desktop', nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('notify', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_status', sa.String(length=16), server_default='never_run', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("device IN ('desktop','mobile_web')", name='ck_test_flows_device'),
    sa.CheckConstraint("last_status IN ('passing','failing','error','never_run')", name='ck_test_flows_last_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_flows_project_id'), 'test_flows', ['project_id'], unique=False)
    op.create_table('tool_call_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('source_client', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('is_write', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_summary', sa.String(length=512), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('response_truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_user_tool_status_ts', 'tool_call_audit', ['user_id', 'tool_name', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_created_at'), 'tool_call_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_is_write'), 'tool_call_audit', ['is_write'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_platform'), 'tool_call_audit', ['platform'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_project_id'), 'tool_call_audit', ['project_id'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_source_client'), 'tool_call_audit', ['source_client'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_status'), 'tool_call_audit', ['status'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_tool_name'), 'tool_call_audit', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_user_id'), 'tool_call_audit', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_conv_seq', 'chat_messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('ga4_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ga4_connection_active', 'ga4_properties', ['connection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_ga4_properties_account_id'), 'ga4_properties', ['account_id'], unique=False)
    op.create_index(op.f('ix_ga4_properties_connection_id'), 'ga4_properties', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ga4_properties_is_active'), 'ga4_properties', ['is_active'], unique=False)
    op.create_table('google_ads_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gads_connection_customer_active', 'google_ads_accounts', ['connection_id', 'customer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_google_ads_accounts_connection_id'), 'google_ads_accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_google_ads_accounts_customer_id'), 'google_ads_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_google_ads_accounts_is_active'), 'google_ads_accounts', ['is_active'], unique=False)
    op.create_table('gtm_containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('container_id', sa.String(length=50), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gtm_connection_account_active', 'gtm_containers', ['connection_id', 'account_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_gtm_containers_account_id'), 'gtm_containers', ['account_id'], unique=False)
    op.create_index(op.f('ix_gtm_containers_connection_id'), 'gtm_containers', ['connection_id'], unique=False)
    op.create_index(op.f('ix_gtm_containers_is_active'), 'gtm_containers', ['is_active'], unique=False)
    op.create_table('kpi_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('binding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_inputs_connection_id'), 'kpi_inputs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_kpi_inputs_kpi_id'), 'kpi_inputs', ['kpi_id'], unique=False)
    op.create_table('member_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_member_id'], ['project_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_member_id', 'role_id', name='uq_member_role')
    )
    op.create_index(op.f('ix_member_roles_project_member_id'), 'member_roles', ['project_member_id'], unique=False)
    op.create_index(op.f('ix_member_roles_role_id'), 'member_roles', ['role_id'], unique=False)
    op.create_table('meta_ads_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meta_connection_account_active', 'meta_ads_accounts', ['connection_id', 'account_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_meta_ads_accounts_account_id'), 'meta_ads_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_meta_ads_accounts_connection_id'), 'meta_ads_accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_meta_ads_accounts_is_active'), 'meta_ads_accounts', ['is_active'], unique=False)
    op.create_table('search_console_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(length=512), nullable=False),
    sa.Column('permission_level', sa.String(length=32), nullable=True),
    sa.Column('is_domain_property', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gsc_connection_site_active', 'search_console_sites', ['connection_id', 'site_url', 'is_active'], unique=False)
    op.create_index(op.f('ix_search_console_sites_connection_id'), 'search_console_sites', ['connection_id'], unique=False)
    op.create_index(op.f('ix_search_console_sites_is_active'), 'search_console_sites', ['is_active'], unique=False)
    op.create_index(op.f('ix_search_console_sites_site_url'), 'search_console_sites', ['site_url'], unique=False)
    op.create_table('snap_ads_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snap_connection_org_account_active', 'snap_ads_accounts', ['connection_id', 'organization_id', 'account_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_snap_ads_accounts_account_id'), 'snap_ads_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_snap_ads_accounts_connection_id'), 'snap_ads_accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_snap_ads_accounts_is_active'), 'snap_ads_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_snap_ads_accounts_organization_id'), 'snap_ads_accounts', ['organization_id'], unique=False)
    op.create_table('test_flow_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('assertions_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assertions_passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('step_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('audit_run_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('running','passing','failing','error')", name='ck_test_flow_runs_status'),
    sa.CheckConstraint("trigger IN ('manual','schedule')", name='ck_test_flow_runs_trigger'),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['test_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_flow_runs_flow_id'), 'test_flow_runs', ['flow_id'], unique=False)
    op.create_index(op.f('ix_test_flow_runs_project_id'), 'test_flow_runs', ['project_id'], unique=False)
    op.create_table('tiktok_ads_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('advertiser_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tiktok_connection_advertiser_active', 'tiktok_ads_accounts', ['connection_id', 'advertiser_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tiktok_ads_accounts_advertiser_id'), 'tiktok_ads_accounts', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_tiktok_ads_accounts_connection_id'), 'tiktok_ads_accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tiktok_ads_accounts_is_active'), 'tiktok_ads_accounts', ['is_active'], unique=False)
    # ### end Alembic commands ###

    # Indexes the ORM models don't declare (expression / partial indexes).
    op.execute("CREATE UNIQUE INDEX uq_kpis_project_slug ON kpis (project_id, lower(slug))")
    op.execute("CREATE UNIQUE INDEX uq_kpis_project_name ON kpis (project_id, lower(name))")
    op.execute("CREATE UNIQUE INDEX uq_kpi_inputs_kpi_key ON kpi_inputs (kpi_id, key)")
    op.execute("CREATE INDEX ix_notifications_user_unread ON notifications (user_id, is_read) WHERE is_read = false")
    op.execute(
        "CREATE UNIQUE INDEX ux_project_email_senders_one_default ON project_email_senders (project_id) "
        "WHERE is_default = true"
    )

    # Composite query indexes (audit history, activity log, roles, KPIs).
    op.execute("CREATE INDEX ix_audit_runs_project_created ON audit_runs (project_id, created_at DESC)")
    op.execute(
        "CREATE INDEX ix_audit_runs_project_type_created ON audit_runs (project_id, audit_type, created_at DESC)"
    )
    op.execute("CREATE INDEX ix_audit_findings_run_severity ON audit_findings (run_id, severity)")
    op.execute("CREATE INDEX ix_audit_findings_run_platform ON audit_findings (run_id, platform)")
    op.execute(
        "CREATE INDEX ix_audit_findings_project_platform_created "
        "ON audit_findings (project_id, platform, created_at DESC)"
    )
    op.execute("CREATE INDEX ix_tool_call_audit_user_created ON tool_call_audit (user_id, created_at)")
    op.execute("CREATE INDEX ix_notifications_created_at ON notifications (user_id, created_at)")
    op.execute("CREATE INDEX ix_roles_project_active ON roles (project_id, is_active)")
    op.execute("CREATE INDEX ix_kpis_status ON kpis (status)")

    # Pre-seed the Claude.ai MCP client.
    op.execute(
        """
        INSERT INTO mcp_clients (id, client_id, client_name, redirect_uris, allowed_scopes, is_public)
        VALUES (
            gen_random_uuid(),
            'claude-ai',
            'Claude.ai',
            ARRAY['https://claude.ai/api/mcp/auth_callback'],
            ARRAY['read'],
            TRUE
        )
        ON CONFLICT (client_id) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_ads_accounts_is_active'), table_name='tiktok_ads_accounts')
    op.drop_index(op.f('ix_tiktok_ads_accounts_connection_id'), table_name='tiktok_ads_accounts')
    op.drop_index(op.f('ix_tiktok_ads_accounts_advertiser_id'), table_name='tiktok_ads_accounts')
    op.drop_index('idx_tiktok_connection_advertiser_active', table_name='tiktok_ads_accounts')
    op.drop_table('tiktok_ads_accounts')
    op.drop_index(op.f('ix_test_flow_runs_project_id'), table_name='test_flow_runs')
    op.drop_index(op.f('ix_test_flow_runs_flow_id'), table_name='test_flow_runs')
    op.drop_table('test_flow_runs')
    op.drop_index(op.f('ix_snap_ads_accounts_organization_id'), table_name='snap_ads_accounts')
    op.drop_index(op.f('ix_snap_ads_accounts_is_active'), table_name='snap_ads_accounts')
    op.drop_index(op.f('ix_snap_ads_accounts_connection_id'), table_name='snap_ads_accounts')
    op.drop_index(op.f('ix_snap_ads_accounts_account_id'), table_name='snap_ads_accounts')
    op.drop_index('idx_snap_connection_org_account_active', table_name='snap_ads_accounts')
    op.drop_table('snap_ads_accounts')
    op.drop_index(op.f('ix_search_console_sites_site_url'), table_name='search_console_sites')
    op.drop_index(op.f('ix_search_console_sites_is_active'), table_name='search_console_sites')
    op.drop_index(op.f('ix_search_console_sites_connection_id'), table_name='search_console_sites')
    op.drop_index('idx_gsc_connection_site_active', table_name='search_console_sites')
    op.drop_table('search_console_sites')
    op.drop_index(op.f('ix_meta_ads_accounts_is_active'), table_name='meta_ads_accounts')
    op.drop_index(op.f('ix_meta_ads_accounts_connection_id'), table_name='meta_ads_accounts')
    op.drop_index(op.f('ix_meta_ads_accounts_account_id'), table_name='meta_ads_accounts')
    op.drop_index('idx_meta_connection_account_active', table_name='meta_ads_accounts')
    op.drop_table('meta_ads_accounts')
    op.drop_index(op.f('ix_member_roles_role_id'), table_name='member_roles')
    op.drop_index(op.f('ix_member_roles_project_member_id'), table_name='member_roles')
    op.drop_table('member_roles')
    op.drop_index(op.f('ix_kpi_inputs_kpi_id'), table_name='kpi_inputs')
    op.drop_index(op.f('ix_kpi_inputs_connection_id'), table_name='kpi_inputs')
    op.drop_table('kpi_inputs')
    op.drop_index(op.f('ix_gtm_containers_is_active'), table_name='gtm_containers')
    op.drop_index(op.f('ix_gtm_containers_connection_id'), table_name='gtm_containers')
    op.drop_index(op.f('ix_gtm_containers_account_id'), table_name='gtm_containers')
    op.drop_index('idx_gtm_connection_account_active', table_name='gtm_containers')
    op.drop_table('gtm_containers')
    op.drop_index(op.f('ix_google_ads_accounts_is_active'), table_name='google_ads_accounts')
    op.drop_index(op.f('ix_google_ads_accounts_customer_id'), table_name='google_ads_accounts')
    op.drop_index(op.f('ix_google_ads_accounts_connection_id'), table_name='google_ads_accounts')
    op.drop_index('idx_gads_connection_customer_active', table_name='google_ads_accounts')
    op.drop_table('google_ads_accounts')
    op.drop_index(op.f('ix_ga4_properties_is_active'), table_name='ga4_properties')
    op.drop_index(op.f('ix_ga4_properties_connection_id'), table_name='ga4_properties')
    op.drop_index(op.f('ix_ga4_properties_account_id'), table_name='ga4_properties')
    op.drop_index('idx_ga4_connection_active', table_name='ga4_properties')
    op.drop_table('ga4_properties')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index('idx_msg_conv_seq', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_tool_call_audit_user_id'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_tool_name'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_status'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_source_client'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_project_id'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_platform'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_is_write'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_created_at'), table_name='tool_call_audit')
    op.drop_index('ix_audit_user_tool_status_ts', table_name='tool_call_audit')
    op.drop_table('tool_call_audit')
    op.drop_index(op.f('ix_test_flows_project_id'), table_name='test_flows')
    op.drop_table('test_flows')
    op.drop_index(op.f('ix_snowflake_connections_warehouse'), table_name='snowflake_connections')
    op.drop_index(op.f('ix_snowflake_connections_user_id'), table_name='snowflake_connections')
    op.drop_index(op.f('ix_snowflake_connections_project_id'), table_name='snowflake_connections')
    op.drop_index(op.f('ix_snowflake_connections_is_active'), table_name='snowflake_connections')
    op.drop_index(op.f('ix_snowflake_connections_database'), table_name='snowflake_connections')
    op.drop_index(op.f('ix_snowflake_connections_connection_status'), table_name='snowflake_connections')
    op.drop_index('idx_snowflake_project_user_active', table_name='snowflake_connections')
    op.drop_table('snowflake_connections')
    op.drop_index(op.f('ix_roles_project_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_redshift_connections_user_id'), table_name='redshift_connections')
    op.drop_index(op.f('ix_redshift_connections_project_id'), table_name='redshift_connections')
    op.drop_index(op.f('ix_redshift_connections_is_active'), table_name='redshift_connections')
    op.drop_index(op.f('ix_redshift_connections_database'), table_name='redshift_connections')
    op.drop_index(op.f('ix_redshift_connections_connection_status'), table_name='redshift_connections')
    op.drop_index('idx_redshift_project_user_active', table_name='redshift_connections')
    op.drop_table('redshift_connections')
    op.drop_index(op.f('ix_project_slack_webhooks_project_id'), table_name='project_slack_webhooks')
    op.drop_table('project_slack_webhooks')
    op.drop_index(op.f('ix_project_oauth_app_credentials_project_id'), table_name='project_oauth_app_credentials')
    op.drop_table('project_oauth_app_credentials')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_invites_project_id'), table_name='project_invites')
    op.drop_index('ix_project_invites_project_email_status', table_name='project_invites')
    op.drop_index(op.f('ix_project_invites_email'), table_name='project_invites')
    op.drop_table('project_invites')
    op.drop_index(op.f('ix_project_email_senders_project_id'), table_name='project_email_senders')
    op.drop_table('project_email_senders')
    op.drop_index(op.f('ix_posthog_connections_user_id'), table_name='posthog_connections')
    op.drop_index(op.f('ix_posthog_connections_project_id'), table_name='posthog_connections')
    op.drop_index(op.f('ix_posthog_connections_is_active'), table_name='posthog_connections')
    op.drop_index(op.f('ix_posthog_connections_connection_status'), table_name='posthog_connections')
    op.drop_index('idx_posthog_project_user_active', table_name='posthog_connections')
    op.drop_table('posthog_connections')
    op.drop_index('ix_oauth_user_active_provider', table_name='oauth_connections')
    op.drop_index('ix_oauth_project_active_provider', table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_provider'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_project_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_is_active'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_connection_status'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_moengage_connections_user_id'), table_name='moengage_connections')
    op.drop_index(op.f('ix_moengage_connections_project_id'), table_name='moengage_connections')
    op.drop_index(op.f('ix_moengage_connections_is_active'), table_name='moengage_connections')
    op.drop_index(op.f('ix_moengage_connections_connection_status'), table_name='moengage_connections')
    op.drop_index('idx_moengage_project_user_active', table_name='moengage_connections')
    op.drop_table('moengage_connections')
    op.drop_index(op.f('ix_mixpanel_connections_user_id'), table_name='mixpanel_connections')
    op.drop_index(op.f('ix_mixpanel_connections_project_id'), table_name='mixpanel_connections')
    op.drop_index(op.f('ix_mixpanel_connections_is_active'), table_name='mixpanel_connections')
    op.drop_index(op.f('ix_mixpanel_connections_connection_status'), table_name='mixpanel_connections')
    op.drop_index('idx_mixpanel_project_user_active', table_name='mixpanel_connections')
    op.drop_table('mixpanel_connections')
    op.drop_index(op.f('ix_marketo_connections_user_id'), table_name='marketo_connections')
    op.drop_index(op.f('ix_marketo_connections_project_id'), table_name='marketo_connections')
    op.drop_index(op.f('ix_marketo_connections_is_active'), table_name='marketo_connections')
    op.drop_index(op.f('ix_marketo_connections_connection_status'), table_name='marketo_connections')
    op.drop_index('idx_marketo_project_user_active', table_name='marketo_connections')
    op.drop_table('marketo_connections')
    op.drop_index(op.f('ix_kpis_project_id'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index('idx_conv_project_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_business_contexts_project_id'), table_name='business_contexts')
    op.drop_table('business_contexts')
    op.drop_index(op.f('ix_braze_connections_user_id'), table_name='braze_connections')
    op.drop_index(op.f('ix_braze_connections_project_id'), table_name='braze_connections')
    op.drop_index(op.f('ix_braze_connections_is_active'), table_name='braze_connections')
    op.drop_index(op.f('ix_braze_connections_connection_status'), table_name='braze_connections')
    op.drop_index('idx_braze_project_user_active', table_name='braze_connections')
    op.drop_table('braze_connections')
    op.drop_index(op.f('ix_branch_connections_user_id'), table_name='branch_connections')
    op.drop_index(op.f('ix_branch_connections_project_id'), table_name='branch_connections')
    op.drop_index(op.f('ix_branch_connections_is_active'), table_name='branch_connections')
    op.drop_index(op.f('ix_branch_connections_connection_status'), table_name='branch_connections')
    op.drop_index('idx_branch_project_user_active', table_name='branch_connections')
    op.drop_table('branch_connections')
    op.drop_index(op.f('ix_bq_connections_user_id'), table_name='bq_connections')
    op.drop_index(op.f('ix_bq_connections_project_id'), table_name='bq_connections')
    op.drop_index(op.f('ix_bq_connections_is_active'), table_name='bq_connections')
    op.drop_index(op.f('ix_bq_connections_fluxito_project_id'), table_name='bq_connections')
    op.drop_index(op.f('ix_bq_connections_connection_status'), table_name='bq_connections')
    op.drop_index('idx_bq_project_user_active', table_name='bq_connections')
    op.drop_table('bq_connections')
    op.drop_index(op.f('ix_audit_vendors_project_id'), table_name='audit_vendors')
    op.drop_table('audit_vendors')
    op.drop_index(op.f('ix_audit_finding_triage_project_id'), table_name='audit_finding_triage')
    op.drop_table('audit_finding_triage')
    op.drop_index(op.f('ix_appsflyer_connections_user_id'), table_name='appsflyer_connections')
    op.drop_index(op.f('ix_appsflyer_connections_project_id'), table_name='appsflyer_connections')
    op.drop_index(op.f('ix_appsflyer_connections_is_active'), table_name='appsflyer_connections')
    op.drop_index(op.f('ix_appsflyer_connections_connection_status'), table_name='appsflyer_connections')
    op.drop_index('idx_appsflyer_project_user_active', table_name='appsflyer_connections')
    op.drop_table('appsflyer_connections')
    op.drop_index(op.f('ix_amplitude_connections_user_id'), table_name='amplitude_connections')
    op.drop_index(op.f('ix_amplitude_connections_project_id'), table_name='amplitude_connections')
    op.drop_index(op.f('ix_amplitude_connections_is_active'), table_name='amplitude_connections')
    op.drop_index(op.f('ix_amplitude_connections_connection_status'), table_name='amplitude_connections')
    op.drop_index('idx_amplitude_project_user_active', table_name='amplitude_connections')
    op.drop_table('amplitude_connections')
    op.drop_index(op.f('ix_adobe_connections_user_id'), table_name='adobe_connections')
    op.drop_index(op.f('ix_adobe_connections_project_id'), table_name='adobe_connections')
    op.drop_index(op.f('ix_adobe_connections_org_id'), table_name='adobe_connections')
    op.drop_index(op.f('ix_adobe_connections_is_active'), table_name='adobe_connections')
    op.drop_index(op.f('ix_adobe_connections_connection_status'), table_name='adobe_connections')
    op.drop_index(op.f('ix_adobe_connections_company_id'), table_name='adobe_connections')
    op.drop_index('idx_adobe_project_user_active', table_name='adobe_connections')
    op.drop_table('adobe_connections')
    op.drop_index(op.f('ix_adjust_connections_user_id'), table_name='adjust_connections')
    op.drop_index(op.f('ix_adjust_connections_project_id'), table_name='adjust_connections')
    op.drop_index(op.f('ix_adjust_connections_is_active'), table_name='adjust_connections')
    op.drop_index(op.f('ix_adjust_connections_connection_status'), table_name='adjust_connections')
    op.drop_index('idx_adjust_project_user_active', table_name='adjust_connections')
    op.drop_table('adjust_connections')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_project_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('oauth_app_credentials')
    op.drop_index(op.f('ix_mcp_sessions_user_id'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sessions_is_revoked'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sessions_access_token_expires_at'), table_name='mcp_sessions')
    op.drop_index('idx_user_active', table_name='mcp_sessions')
    op.drop_table('mcp_sessions')
    op.drop_index(op.f('ix_mcp_auth_codes_user_id'), table_name='mcp_auth_codes')
    op.drop_index(op.f('ix_mcp_auth_codes_used'), table_name='mcp_auth_codes')
    op.drop_index(op.f('ix_mcp_auth_codes_expires_at'), table_name='mcp_auth_codes')
    op.drop_index('idx_code_unused_valid', table_name='mcp_auth_codes')
    op.drop_table('mcp_auth_codes')
    op.drop_index(op.f('ix_audit_findings_run_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_project_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_table('ai_provider_keys')
    op.drop_index(op.f('ix_access_requests_email'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tag_custom_rules_project_id'), table_name='tag_custom_rules')
    op.drop_table('tag_custom_rules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('mcp_clients')
    op.drop_index(op.f('ix_ltt_test_plans_project_id'), table_name='ltt_test_plans')
    op.drop_table('ltt_test_plans')
    op.drop_index(op.f('ix_audit_runs_project_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    # ### end Alembic commands ###
