"""First-boot secret bootstrap (hybrid model).

Only APP_SECRET_KEY and TOKEN_ENCRYPTION_KEY are auto-generated here.
All other configuration (platform OAuth apps, email, dashboards,
observability, rate limits, etc.) lives in the database and is managed
via the web UI after first boot.

If the two crypto keys are missing from the environment, this module
generates sane values and writes them to `.env.local` (gitignored).
The .env.local file is loaded on subsequent boots.

This runs ONCE per process at import time. Idempotent.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

from cryptography.fernet import Fernet

_ENV_LOCAL = Path(__file__).resolve().parent.parent / ".env.local"


def _generate_app_secret_key() -> str:
    """64 hex chars (32 bytes) — overkill but cheap."""
    return secrets.token_hex(32)


def _generate_token_encryption_key() -> str:
    """Fernet expects a 32-byte url-safe base64 key."""
    return Fernet.generate_key().decode()


def _load_env_local() -> dict[str, str]:
    """Parse .env.local into a dict. Returns {} if file doesn't exist."""
    if not _ENV_LOCAL.exists():
        return {}
    out: dict[str, str] = {}
    for line in _ENV_LOCAL.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_env_local(values: dict[str, str]) -> None:
    """Write key=value pairs to .env.local. Preserves existing keys it doesn't manage."""
    existing = _load_env_local()
    existing.update(values)
    body = (
        (
            "# Auto-generated by Fluxito on first boot. Safe to edit, but keys\n"
            "# managed by the app (APP_SECRET_KEY, TOKEN_ENCRYPTION_KEY) will be\n"
            "# regenerated if missing.\n"
            "\n"
        )
        + "\n".join(f"{k}={v}" for k, v in sorted(existing.items()))
        + "\n"
    )
    _ENV_LOCAL.write_text(body)
    try:
        _ENV_LOCAL.chmod(0o600)
    except OSError:
        # Best-effort on platforms that don't support chmod (Windows etc.)
        pass


def bootstrap_secrets() -> None:
    """Ensure APP_SECRET_KEY and TOKEN_ENCRYPTION_KEY exist in os.environ.

    Resolution order:
      1. Already in os.environ (from .env or the shell) — leave alone.
      2. Already in .env.local — load into os.environ.
      3. Neither — generate, write to .env.local, set in os.environ.
    """
    env_local = _load_env_local()
    generated: dict[str, str] = {}

    for key, generator in (
        ("APP_SECRET_KEY", _generate_app_secret_key),
        ("TOKEN_ENCRYPTION_KEY", _generate_token_encryption_key),
    ):
        if os.environ.get(key):
            continue
        if env_local.get(key):
            os.environ[key] = env_local[key]
            continue
        value = generator()
        os.environ[key] = value
        generated[key] = value

    if generated:
        _write_env_local(generated)
